
[project]
name = "sz_detection_challenge"


[datasets]
# Paths to BIDS datasets
data_dir = "I:/Chercheurs/BouAssi_Elie/Data/SeizureDetectionChallenge2025/"
tuh_sz_bids = "BIDS_tuh_eeg_seizure"
chb_mit_bids = "BIDS_CHB-MIT"
siena_bids = "BIDS_Siena"


[labels]
labels_file = "data/cleaned/labels.parquet"

[features]
features_config = "features_config.yaml"
feature_db_file = "data/cleaned/features.db"
num_workers = 40

[runtime]
debug = true