
[project]
name = 'sz_detection_challenge'

[datasets]
# Paths to BIDS datasets
tuh_sz_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_tuh_eeg_seizure"
# chb_mit_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_CHB-MIT"
siena_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_Siena"

[utilities]
bids_db_files_dir = "data/temp/bids_db"

[labels]
labels_file = "data/cleaned/labels.parquet"

[features]
features_config = "features_config.yaml"
features_dir = "data/cleaned/features_v3/"
features_db_file = "data/cleaned/features.db"
num_workers = 4
overwrite = false
log_dir = "logs/features_v3"

[preprocessing]
# -1 will be converted to None
read_edf.channels = -1 # Default to the 19 channels in 10-20 system
filter_eeg.l_freq = 1
filter_eeg.h_freq = 99
filter_eeg.notch = -1
segment_eeg.window_duration = 10
segment_eeg.overlap = 10

[runtime]
debug = false

