
[project]
name = 'sz_detection_challenge'

[datasets]
# Paths to BIDS datasets
tuh_sz_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_tuh_eeg_seizure"
chb_mit_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_CHB-MIT"
siena_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_Siena"

[labels]
labels_file = "data/cleaned/labels.parquet"

[features]
features_config = "features_config.yaml"
features_db_file = "data/cleaned/features.db"
num_workers = 4

[runtime]
debug = true