
[project]
name = 'sz_detection_challenge'

[datasets]
# Paths to BIDS datasets
tuh_sz_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_tuh_eeg_seizure"
chb_mit_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_CHB-MIT"
siena_bids = "/mnt/data/SeizureDetectionChallenge2025/BIDS_Siena"

[utilities]
bids_db_files_dir = "data/temp/bids_db"

[labels]
labels_file = "data/cleaned/labels.parquet"

[features]
features_config = "features_config.yaml"
features_dir = "data/cleaned/features/"
features_db_file = "data/cleaned/features.db"
num_workers = 1

[preprocessing]
# -1 will be converted to None
read_edf.channels = -1 # Default to the 19 channels in 10-20 system
filter_eeg.l_freq = 1
filter_eeg.h_freq = 99
filter_eeg.notch_filter = -1
resample_eeg.sfreq = 200
segment_eeg.window_duration = 10
segment_eeg.overlap = 1

[results]
results_dir = "data/results"

[runtime]
debug = true

[logs]
log_file = 'data/log_files/test_ml_run.log'