features:
  tf_decomposition:
    - name: fuzzen
      function: univariate.fuzzy_entropy
      params:
        m: [2]
        r: [0.2]
    - name: linelength
      function: univariate.line_length
      params:
    - name: corr_dim
      function: univariate.corr_dim
      params:
        embed_dim: 3
  simple:
    - name: band_power
      function: univariate.band_power
      params:
        band_ranges:
          - - !!python/tuple [1, 4]
            - !!python/tuple [4, 8]
            - !!python/tuple [8, 13]
            - !!python/tuple [13, 25]
            - !!python/tuple [25, 40]
            - !!python/tuple [40, 80]
    - name: peak_alpha
      function: univariate.peak_alpha
      params:
  connectivity:
    - name: average_shortest_path_length
      function: connectivity.average_shortest_path_length
      params:
    - name: betweenness
      function: szdetect.centrality_features.betweenness
      params:
    - name: diversity_coef
      function: szdetect.centrality_features.diversity_coef
      params:
    - name: node_betweenness
      function: szdetect.centrality_features.node_betweenness
      params:
    - name: participation_coef
      function: szdetect.centrality_features.participation_coef
      params:
    - name: module_degree_zscore
      function: szdetect.centrality_features.module_degree_zscore
      params:
    - name: eigenvector_centrality
      function: szdetect.centrality_features.eigenvector_centrality
      params:
    - name: efficiency
      function: szdetect.efficiency_features.efficiency
      params:
    - name: global_diffusion_efficiency
      function: szdetect.efficiency_features.global_diffusion_efficiency
      params:
    - name: global_rout_efficiency
      function: szdetect.efficiency_features.global_rout_efficiency
      params:
    - name: local_rout_efficiency
      function: szdetect.efficiency_features.local_rout_efficiency
      params:
    - name: node_degree
      function: szdetect.connectivity.node_degree
      params:
    - name: node_strength
      function: szdetect.connectivity.node_strength
      params:
    - name: transitivity
      function: szdetect.connectivity.transitivity
      params:
    - name: eigenvalues
      function: szdetect.connectivity.eigenvalues
      params:
    # - name: node_degree
    #   function: szdetect.connectivity.upper_right_triangle  # INVALID SHAPE
    #   params:

frameworks:
  tf_decomposition:
    - name: dwt
      function: timefrequency.dwt_eeg
      params:
        wavelet: sym5
        max_level: 6
  simple:
    - name: simple
      function: null
      params: null
  connectivity:
    - name: corr
      function: connectivity.spectral_connectivity
      params:
        freqs:
          - !!python/tuple [1, 4]
          - !!python/tuple [4, 8]
          - !!python/tuple [8, 13]
          - !!python/tuple [13, 25]
          - !!python/tuple [25, 40]
          - !!python/tuple [40, 80]
          - !!python/tuple [3, 40]
        method: corr
        wavelet: cmor1.5-1.0
