features:
  tf_decomposition:
    - name: fuzzen
      function: univariate.fuzzy_entropy
      params:
        m: [2]
        r: [0.2]
    - name: linelength
      function: univariate.line_length
      params:
  simple:
    - name: band_power
      function: univariate.band_power
      params:
        freqs:
          - - !!python/tuple [1, 2]
            - !!python/tuple [2, 4]
            - !!python/tuple [4, 6]
            - !!python/tuple [6, 8]
            - !!python/tuple [8, 13]
            - !!python/tuple [13, 30]
            - !!python/tuple [30, 50]
            - !!python/tuple [50, 80]
  connectivity:
    - name: betweenness
      function: szdetect.centrality_features.betweenness
      params:
    - name: eigenvector_centrality
      function: szdetect.centrality_features.eigenvector_centrality
      params:
    - name: efficiency
      function: szdetect.efficiency_features.efficiency
      params:
    - name: global_diffusion_efficiency
      function: szdetect.efficiency_features.global_diffusion_efficiency
      params:
    - name: node_strength
      function: szdetect.connectivity.node_strength
      params:
    - name: transitivity
      function: szdetect.connectivity.transitivity
      params:

frameworks:
  tf_decomposition:
    - name: cwt
      function: timefrequency.cwt_eeg
      params:
        freqs:
          - - !!python/tuple [3, 4]
            - !!python/tuple [4, 6]
            - !!python/tuple [6, 8]
            - !!python/tuple [8, 13]
            - !!python/tuple [13, 20]
            - !!python/tuple [20, 30]
            - !!python/tuple [30, 50]
            - !!python/tuple [3, 40]
        skip_reconstr: [True]
        skip_complex: [True]
  simple:
    - name: simple
      function: null
      params: null
  connectivity:
    - name: corr
      function: connectivity.connectivity_from_coeff
      params:
        freqs:
          - - !!python/tuple [3, 4]
            - !!python/tuple [4, 6]
            - !!python/tuple [6, 8]
            - !!python/tuple [8, 13]
            - !!python/tuple [13, 20]
            - !!python/tuple [20, 30]
            - !!python/tuple [30, 50]
            - !!python/tuple [3, 40]
        method: corr
        wavelet: cmor1.5-1.0
