features:
  tf_decomposition:
    - name: fuzzen
      function: univariate.fuzzy_entropy
      params:
        m: [2]
        r: [0.2]
    - name: linelength
      function: univariate.line_length
      params:
  simple:
    - name: band_power
      function: univariate.band_power
      params:
        freqs:
          - - !!python/tuple [1, 4]
            - !!python/tuple [4, 8]
            - !!python/tuple [8, 13]
            - !!python/tuple [13, 25]
            - !!python/tuple [25, 40]
            - !!python/tuple [40, 80]
  connectivity:
    - name: betweenness
      function: szdetect.centrality_features.betweenness
      params:
    - name: diversity_coef
      function: szdetect.centrality_features.diversity_coef
      params:
    - name: node_betweenness
      function: szdetect.centrality_features.node_betweenness
      params:
    - name: participation_coef
      function: szdetect.centrality_features.participation_coef
      params:
    - name: module_degree_zscore
      function: szdetect.centrality_features.module_degree_zscore
      params:
    - name: eigenvector_centrality
      function: szdetect.centrality_features.eigenvector_centrality
      params:
    - name: efficiency
      function: szdetect.efficiency_features.efficiency
      params:
    - name: global_diffusion_efficiency
      function: szdetect.efficiency_features.global_diffusion_efficiency
      params:
    - name: global_rout_efficiency
      function: szdetect.efficiency_features.global_rout_efficiency
      params:
    - name: local_rout_efficiency
      function: szdetect.efficiency_features.local_rout_efficiency
      params:
    - name: node_degree
      function: szdetect.connectivity.node_degree
      params:
    - name: node_strength
      function: szdetect.connectivity.node_strength
      params:
    - name: transitivity
      function: szdetect.connectivity.transitivity
      params:
    - name: eigenvalues
      function: szdetect.connectivity.eigenvalues
      params:

frameworks:
  tf_decomposition:
    - name: cwt
      function: timefrequency.cwt_eeg
      params:
        freqs:
          - - !!python/tuple [1, 4]
            - !!python/tuple [4, 8]
            - !!python/tuple [8, 13]
            - !!python/tuple [13, 25]
            - !!python/tuple [25, 40]
            - !!python/tuple [3, 40]
  simple:
    - name: simple
      function: null
      params: null
  connectivity:
    - name: corr
      function: connectivity.connectivity_from_coeff
      params:
        freqs:
          - - !!python/tuple [1, 4]
            - !!python/tuple [4, 8]
            - !!python/tuple [8, 13]
            - !!python/tuple [13, 25]
            - !!python/tuple [25, 40]
            - !!python/tuple [3, 40]
        method: corr
        wavelet: cmor1.5-1.0
